name: tourist_app
description: Your app description
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  injectable: ^2.3.0
  go_router: ^11.1.2
  logger: ^2.0.2+1
  intl: ^0.19.0
  equatable: ^2.0.7
  geolocator: ^14.0.0
  mapbox_maps_flutter: ^2.8.0
  permission_handler: ^12.0.0+1
  modal_bottom_sheet: ^3.0.0
  http: ^1.1.0
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  intl_utils: ^2.8.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated